name: news_watch

description: "A poject for news (Midad Training)"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  animated_floating_buttons: ^0.0.2
  # slider_button: ^2.1.0
  bot_toast: ^4.1.3
  icons_launcher: ^3.0.0
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  responsive_framework: ^1.5.1 
  shared_preferences: ^2.3.3
  json_theme_plus: ^6.8.0
  i18n_extension: ^15.0.0
  i18n_extension_importer: ^0.0.6
  go_router: ^14.6.1 
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  reactive_forms: ^17.0.1
  reactive_phone_form_field: ^5.0.1
  reactive_flutter_rating_bar: ^2.0.1
  reactive_dropdown_search: ^5.0.5
  reactive_pinput: ^5.0.0
  flutter_quill: ^11.0.0
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.10.1 # Core for Firebase
  cloud_firestore: ^5.6.2 # For Could Firestore Database
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  font_awesome_flutter: ^10.8.0
  country_flags: ^3.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  intl: ^0.19.0
  share_plus: ^10.1.4
  firebase_messaging: ^15.2.3
  googleapis_auth: ^1.6.0
  dio: ^5.8.0+1
  change_app_package_name: ^1.5.0
  lottie: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4

# dependencies_overrides:
  # vibration: ^3.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/themes/
    - assets/translations/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    android:
      enable: true
    web:
      enable: true